# Always name every file that holds and action as "action"
name: 'Get & Cache Dependencies'
description: 'Get the dependencies (via npm) and cache them.'
inputs: # Using input when called
  caching: # Whatever name
    description: 'Whether to cache dependencies or not.'
    required: false
    default: 'true'
runs: # Must
  using: 'composite' # Type of action
  steps:
    - name: Cache dependencies
      if: inputs.caching # retrieving caching input value
      id: cache
      uses: actions/cache@v3
      with:
        path: node_modules
        key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
    - name: Install dependencies
      if: steps.cache.outputs.cache-hit != 'true' || inputs.caching != 'true' # If there's no cache yet or if caching is false, will install
      run: npm ci
      shell: bash # When running commands, shell must be set
